# Generated by Django 3.2.5 on 2022-07-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nonconformanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_nonconformance',
            name='Category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='add_nonconformance',
            name='Part_Location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='add_nonconformance',
            name='Part_Num',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='add_nonconformance',
            name='Type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='Barcode_Horizontal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='Barcode_Vertical',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='Category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='Computer_SN',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='Doc_Num',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='Inspector',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='Instrument_SN',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='Issue_Num',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='Name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ref_nonconformance',
            name='Category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ref_nonconformance',
            name='Part_Num',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ref_nonconformance',
            name='Type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
