# Generated by Django 3.2.5 on 2022-07-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nonconformanceapp', '0002_auto_20220729_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref_nonconformance',
            name='Part_Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ref_nonconformance',
            name='Part_Num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
