version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
  django_container_gunicorn:
    image: django_test_image:4
    networks:
      - network
    volumes:
      - static-volume:/home/Inst_QC/staticfiles
      - media-volume:/home/Inst_QC/media

    # 서비스 명
    db:
      image: nouchka/sqlite:latest
      volumes:
        - ./data/db:root/db
      enviroment:
        - SQLITE3_DB=db.sqlite3
        -

#  mariadb:
#    image: postgresql
#    networks:
#      - network
#    volumes:
#    - maria-database:/var/lib/postgresql
#    environment:
#      MYSQL_ROOT_PASSWORD: password1234
#      MYSQL_DATABASE: mydatabase
#      MYSQL_USER: django
#      MYSQL_PASSWORD: password1234

networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-database:
