# Generated by Django 4.0.3 on 2022-03-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.CharField(max_length=60),
        ),
    ]
