# Generated by Django 4.0.3 on 2022-04-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_alter_category_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='subcategory',
            new_name='Subcategory',
        ),
    ]
