# Generated by Django 4.0.3 on 2022-05-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0001_initial'),
        ('FinishedInspectionapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inspection',
            new_name='Finish_Inspection',
        ),
    ]
