# Generated by Django 4.0.3 on 2022-05-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0001_initial'),
        ('FinishedInspectionapp', '0002_rename_inspection_finish_inspection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finish_Inspection',
            new_name='FinishInspection',
        ),
    ]
