# Generated by Django 4.0.3 on 2022-05-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinishedInspectionapp', '0003_rename_finish_inspection_finishinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishinspection',
            name='Computer_SN',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
