# Generated by Django 4.0.3 on 2022-05-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0001_initial'),
        ('FinishedInspectionapp', '0005_rename_fw_master_finishinspection_barcode_scanner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishinspection',
            name='Instrument_SN',
            field=models.ForeignKey(db_column='Instrument_SN', on_delete=django.db.models.deletion.CASCADE, related_name='Finished_Instrument_SN', to='Instrumentapp.instrument'),
        ),
    ]
