# Generated by Django 4.0.3 on 2022-05-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccesorieKitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='Remark',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
