# Generated by Django 4.0.3 on 2022-05-20 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccesorieKitapp', '0002_accessories_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='MeasurementProtocolSTARlet',
        ),
    ]
