# Generated by Django 4.0.3 on 2022-07-11 06:04

import AccesorieKitapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0001_initial'),
        ('AccesorieKitapp', '0003_remove_accessories_measurementprotocolstarlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unpack_Instructions_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Installation_Qualification_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Final_Configuation_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Measurement_Protocol_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('EU_Declaration_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('DeclarationSTARlet_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Declaration_Quality_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Packing_Checklist_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Maintenance_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Channel_Adjust_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Test_Report_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Loading_Table_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Side_Cover_right_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Side_Cover_left_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Rear_Piexiglas_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Top_Plexiglas_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Left_Plexiglas_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Right_Plexiglas_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Sensor_4L_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Solid_Waste_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('USB_Liquid_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('USB_Solid_Liquid_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('USB_Venus_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Eppendorf_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Core_Gripper_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Needle_Check_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Needle_Lot_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Separator_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Tip_Eject_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Power_Cord7_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Power_CordP_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Cable_USB_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Fuse_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Screw_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Fitting_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Liq_Waste_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('XArm_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Bar_Left_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Bar_Top_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Bag_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Tube_32_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('TipRack_5_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('MFX4_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('SEEG_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('FLHX_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('SOHX_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('HHS_Plate_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('MTP_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Verify_Kit_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('STD_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('High_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('HHS_SN_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('HHS_Check_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('HHS_Manual_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Stop_Barcode_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Remark_Files', models.FileField(blank=True, null=True, upload_to=AccesorieKitapp.models.AccessoriesFiles.AccessoriesFiles_path)),
                ('Instrument_SN', models.ForeignKey(db_column='Instrument_SN', on_delete=django.db.models.deletion.CASCADE, related_name='AccFile_Instrument_SN', to='Instrumentapp.instrument')),
            ],
        ),
    ]
