# Generated by Django 4.0.3 on 2022-07-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccesorieKitapp', '0005_alter_accessories_bag_alter_accessories_bar_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoriesfiles',
            name='Needle_Lot_Files',
        ),
    ]
