# Generated by Django 4.0.3 on 2022-07-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('SN', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instrument', models.CharField(choices=[('공용', '공용'), ('Seegene STARlet', 'Seegene STARlet'), ('Hamilton STARlet', 'Hamilton STARlet'), ('Seegene Nimbus', 'Seegene Nimbus'), ('CFX 96Dx', 'CFX 96Dx'), ('Seeprep32', 'Seeprep32'), ('SGRT', 'SGRT'), ('AIOS', 'AIOS'), ('VCMS', 'VCMS'), ('모바일스테이션', '모바일스테이션'), ('기타', '기타')], default='Seegene STARlet', max_length=32, verbose_name='장비이름')),
                ('Report_Category', models.CharField(choices=[('Inspection Report', '수입검사 성적서'), ('Finished Product Report', '완제품검사 성적서'), ('Finished Product Report Rev', '완제품 지침서'), ('Finished Label', '완제품 라벨')], max_length=40, verbose_name='성적서 종류')),
                ('Management_Num', models.CharField(max_length=50, verbose_name='관리번호')),
                ('Rev', models.IntegerField()),
                ('Start_Dt', models.DateField(blank=True, null=True, verbose_name='사용 시작일')),
                ('End_Dt', models.DateField(blank=True, null=True, verbose_name='사용 종료일')),
                ('Etc', models.CharField(blank=True, max_length=300, null=True, verbose_name='관리번호')),
            ],
            options={
                'verbose_name': '개정문서 데이터',
                'verbose_name_plural': '개정문서 데이터',
                'db_table': 'instrumentapp_revision',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instrument', models.CharField(choices=[('공용', '공용'), ('Seegene STARlet', 'Seegene STARlet'), ('Hamilton STARlet', 'Hamilton STARlet'), ('Seegene Nimbus', 'Seegene Nimbus'), ('CFX 96Dx', 'CFX 96Dx'), ('Seeprep32', 'Seeprep32'), ('SGRT', 'SGRT'), ('AIOS', 'AIOS'), ('VCMS', 'VCMS'), ('모바일스테이션', '모바일스테이션'), ('기타', '기타')], default='Seegene STARlet', max_length=32, verbose_name='장비이름')),
                ('Inst_Label_Kor', models.CharField(blank='장비라벨(국문)', max_length=50)),
                ('Box_Label_Kor', models.CharField(blank='박스라벨(국문)', max_length=50)),
                ('Inst_Label_Eng', models.CharField(blank='박스라벨(영문)', max_length=50)),
                ('Box_Label_Eng', models.CharField(blank='박스라벨(영문)', max_length=50)),
                ('Etc', models.CharField(blank=True, max_length=300, null=True, verbose_name='비고란')),
            ],
            options={
                'verbose_name': '장비 버전관리 데이터',
                'verbose_name_plural': '장비 버전관리 데이터',
                'db_table': 'instrumentapp_version',
            },
        ),
    ]
