# Generated by Django 4.0.3 on 2022-07-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='End_Dt',
            new_name='Expiry_Dt',
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='Instrument',
            new_name='Instrument_Name',
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='Rev',
            new_name='Revision',
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='Report_Category',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='Etc',
        ),
        migrations.AddField(
            model_name='revision',
            name='Remarks',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='revision',
            name='Rev_UpperMNG_Rev',
            field=models.IntegerField(default=1, verbose_name='상위 관리번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='UpperMNG_Num',
            field=models.CharField(default=1, max_length=50, verbose_name='관리번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='UpperRev_Date',
            field=models.DateField(blank=True, null=True, verbose_name='지침서 개정일'),
        ),
    ]
