# Generated by Django 4.0.3 on 2022-07-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'verbose_name': '개정문서 데이터', 'verbose_name_plural': '개정문서 데이터'},
        ),
        migrations.AlterModelTable(
            name='revision',
            table='instrumentapp_revision',
        ),
    ]
