# Generated by Django 4.0.3 on 2022-07-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0002_rename_end_dt_revision_expiry_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='Instrument',
            new_name='Instrument_Name',
        ),
        migrations.AddField(
            model_name='version',
            name='Barcode_Scanner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='바코드 스캐너'),
        ),
        migrations.AddField(
            model_name='version',
            name='DAC0',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='님부스 DACO'),
        ),
        migrations.AddField(
            model_name='version',
            name='Door_Lock',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='님부스 도어락'),
        ),
        migrations.AddField(
            model_name='version',
            name='Expiry_Dt',
            field=models.DateField(blank=True, null=True, verbose_name='사용 종료일'),
        ),
        migrations.AddField(
            model_name='version',
            name='Extraction_System',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SeePrep32 Extraction System'),
        ),
        migrations.AddField(
            model_name='version',
            name='FV2_Version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='해밀턴 FV2 버전'),
        ),
        migrations.AddField(
            model_name='version',
            name='Firmware',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SeePrep32 Firmware'),
        ),
        migrations.AddField(
            model_name='version',
            name='IO_Board',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IO 보드'),
        ),
        migrations.AddField(
            model_name='version',
            name='Launcher_Version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='런처 버전'),
        ),
        migrations.AddField(
            model_name='version',
            name='Master',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='마스터 버전'),
        ),
        migrations.AddField(
            model_name='version',
            name='Nimbus_CORE',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='님부스 CO-RE'),
        ),
        migrations.AddField(
            model_name='version',
            name='Pipette_Ch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='파이펫 채널 버전'),
        ),
        migrations.AddField(
            model_name='version',
            name='SW_Version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='해밀턴 S/W 버전'),
        ),
        migrations.AddField(
            model_name='version',
            name='Start_Dt',
            field=models.DateField(blank=True, null=True, verbose_name='사용 시작일'),
        ),
        migrations.AddField(
            model_name='version',
            name='X_drive',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='X-Drive 버전'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='Rev_UpperMNG_Rev',
            field=models.IntegerField(verbose_name='상위 Reivision'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='Type',
            field=models.CharField(choices=[('Inspection Report', '수입검사 성적서'), ('Finished Product Report', '완제품검사 성적서'), ('Finished Product Report Rev', '완제품 지침서'), ('Finished Label', '완제품 라벨')], max_length=40, verbose_name='문서 구분'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='UpperMNG_Num',
            field=models.CharField(max_length=50, verbose_name='상위 관리번호'),
        ),
        migrations.AlterField(
            model_name='version',
            name='Box_Label_Eng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='박스라벨(영문)'),
        ),
        migrations.AlterField(
            model_name='version',
            name='Box_Label_Kor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='박스라벨(국문)'),
        ),
        migrations.AlterField(
            model_name='version',
            name='Inst_Label_Eng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='박스라벨(영문)'),
        ),
        migrations.AlterField(
            model_name='version',
            name='Inst_Label_Kor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='장비라벨(국문)'),
        ),
    ]
