# Generated by Django 4.0.3 on 2022-07-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0002_alter_revision_options_alter_revision_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='Rev_Num',
        ),
        migrations.AddField(
            model_name='revision',
            name='Etc',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='관리번호'),
        ),
        migrations.AddField(
            model_name='revision',
            name='Management_Num',
            field=models.CharField(default=1, max_length=50, verbose_name='관리번호'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revision',
            name='End_Dt',
            field=models.DateField(blank=True, null=True, verbose_name='사용 종료일'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='Start_Dt',
            field=models.DateField(blank=True, null=True, verbose_name='사용 시작일'),
        ),
    ]
