# Generated by Django 4.0.3 on 2022-04-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0003_instrument_computer_sn_instrument_fv2_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='Completed_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='Start_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
