# Generated by Django 4.0.3 on 2022-07-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0003_remove_revision_rev_num_revision_etc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instrument', models.CharField(choices=[('공용', '공용'), ('Seegene STARlet', 'Seegene STARlet'), ('Hamilton STARlet', 'Hamilton STARlet'), ('Seegene Nimbus', 'Seegene Nimbus'), ('CFX 96Dx', 'CFX 96Dx'), ('Seeprep32', 'Seeprep32'), ('SGRT', 'SGRT'), ('AIOS', 'AIOS'), ('VCMS', 'VCMS'), ('모바일스테이션', '모바일스테이션'), ('기타', '기타')], default='Seegene STARlet', max_length=32, verbose_name='장비이름')),
                ('Inst_Label_Kor', models.CharField(blank='장비라벨(국문)', max_length=50)),
                ('Box_Label_Kor', models.CharField(blank='박스라벨(국문)', max_length=50)),
                ('Inst_Label_Eng', models.CharField(blank='박스라벨(영문)', max_length=50)),
                ('Box_Label_Eng', models.CharField(blank='박스라벨(영문)', max_length=50)),
                ('Etc', models.CharField(blank=True, max_length=300, null=True, verbose_name='관리번호')),
            ],
            options={
                'verbose_name': '장비 버전관리 데이터',
                'verbose_name_plural': '장비 버전관리 데이터',
                'db_table': 'instrumentapp_version',
            },
        ),
    ]
