# Generated by Django 4.0.3 on 2022-07-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0004_alter_version_box_label_eng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='Barcode_Scanner',
        ),
        migrations.RemoveField(
            model_name='version',
            name='Box_Label_Eng',
        ),
        migrations.RemoveField(
            model_name='version',
            name='Box_Label_Kor',
        ),
        migrations.RemoveField(
            model_name='version',
            name='DAC0',
        ),
        migrations.RemoveField(
            model_name='version',
            name='Door_Lock',
        ),
        migrations.RemoveField(
            model_name='version',
            name='Extraction_System',
        ),
        migrations.RemoveField(
            model_name='version',
            name='FV2_Version',
        ),
        migrations.RemoveField(
            model_name='version',
            name='Firmware',
        ),
        migrations.RemoveField(
            model_name='version',
            name='IO_Board',
        ),
        migrations.RemoveField(
            model_name='version',
            name='Inst_Label_Eng',
        ),
        migrations.RemoveField(
            model_name='version',
            name='Inst_Label_Kor',
        ),
        migrations.RemoveField(
            model_name='version',
            name='Launcher_Version',
        ),
        migrations.RemoveField(
            model_name='version',
            name='Master',
        ),
        migrations.RemoveField(
            model_name='version',
            name='Nimbus_CORE',
        ),
        migrations.RemoveField(
            model_name='version',
            name='Pipette_Ch',
        ),
        migrations.RemoveField(
            model_name='version',
            name='SW_Version',
        ),
        migrations.RemoveField(
            model_name='version',
            name='X_drive',
        ),
        migrations.AddField(
            model_name='version',
            name='SW_Name',
            field=models.CharField(choices=[('Microlab STAR Maintenance & Verification', 'Microlab STAR Maintenance & Verification'), ('STARlet Service-Shortcut Software', 'STARlet Service-Shortcut Software'), ('Hamilton STARlet', 'Hamilton STARlet'), ('VCMS Service Software', 'VCMS Service Software'), ('FourProbeCalibration', 'FourProbeCalibration'), ('Hamilton S/W Version', 'Hamilton S/W Version'), ('Hamilton FV2 Version', 'Hamilton FV2 Version'), ('Pipette Ch (PX)', 'Pipette Ch (PX)'), ('X-drive (XO)', 'X-drive (XO)'), ('Master (CO)', 'Master (CO)'), ('Inst_Label_Kor', '국문 장비 라벨'), ('Box_Label_Kor', '국문 박스 라벨'), ('Inst_Label_Eng', '영문 장비 라벨'), ('Box_Label_Eng', '영문 박스 라벨'), ('Seegene Launcher Version', 'Seegene Launcher Version'), ('Left/Right Door Lock', 'Left/Right Door Lock'), ('DAC0', 'DAC0'), ('Seegene Launcher Version', 'Seegene Launcher Version')], default='Seegene Launcher Version', max_length=100, verbose_name='SW 이름'),
        ),
    ]
