# Generated by Django 4.0.3 on 2022-07-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0005_remove_version_barcode_scanner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='Type',
            field=models.CharField(choices=[('지침서용', '지침서용'), ('성적서용', '성적서용')], default=1, max_length=40, verbose_name='문서 구분'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='version',
            name='SW_Name',
            field=models.CharField(choices=[('Microlab STAR Maintenance & Verification', 'Microlab STAR Maintenance & Verification'), ('STARlet Service-Shortcut Software', 'STARlet Service-Shortcut Software'), ('Hamilton STARlet', 'Hamilton STARlet'), ('VCMS Service Software', 'VCMS Service Software'), ('FourProbeCalibration', 'FourProbeCalibration'), ('Hamilton S/W Version', 'Hamilton S/W Version'), ('Hamilton FV2 Version', 'Hamilton FV2 Version'), ('Pipette Ch (PX)', 'Pipette Ch (PX)'), ('X-drive (XO)', 'X-drive (XO)'), ('Master (CO)', 'Master (CO)'), ('Inst_Label_Kor', '국문 장비 라벨'), ('Box_Label_Kor', '국문 박스 라벨'), ('Inst_Label_Eng', '영문 장비 라벨'), ('Box_Label_Eng', '영문 박스 라벨'), ('Hamilton S/W Version', 'Hamilton S/W Version'), ('Nimbus CO-RE', 'Nimbus CO-RE'), ('DAC0', 'DAC0'), ('Left/Right Door Lock', 'Left/Right Door Lock'), ('Barcode Scanner', 'Barcode Scanner'), ('Extraction System S/W Version', 'Extraction System S/W Version'), ('Firmware Version', 'Firmware Version'), ('Seegene Launcher Version', 'Seegene Launcher Version')], default='Seegene Launcher Version', max_length=100, verbose_name='SW 이름'),
        ),
    ]
