# Generated by Django 4.0.3 on 2022-07-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0007_remove_version_etc_version_remarks_version_sw_ver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='Type',
            field=models.CharField(choices=[('Inspection Report', '수입검사 성적서'), ('Finished Product Report', '완제품검사 성적서'), ('Finished Product Report Rev', '완제품 지침서'), ('Finished Label', '완제품 라벨'), ('Labelling & Packaging Instruction', '라벨링 포장 지침서')], max_length=40, verbose_name='문서 구분'),
        ),
    ]
