# Generated by Django 4.0.3 on 2022-04-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0007_inspection_remove_instrument_completed_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
