# Generated by Django 4.0.3 on 2022-07-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0008_alter_revision_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='Rev_UpperMNG_Rev',
            field=models.IntegerField(blank=True, null=True, verbose_name='상위 Reivision'),
        ),
    ]
