# Generated by Django 4.0.3 on 2022-04-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0008_delete_inspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='id',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='SN',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
