# Generated by Django 4.0.3 on 2022-07-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0009_alter_revision_rev_uppermng_rev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='UpperMNG_Num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='상위 관리번호'),
        ),
    ]
