# Generated by Django 4.0.3 on 2022-04-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0009_remove_instrument_id_alter_instrument_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrument',
            name='SN',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
