# Generated by Django 4.0.3 on 2022-07-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0011_alter_revision_instrument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='Instrument_Name',
            field=models.CharField(choices=[('Seegene STARlet', 'Seegene STARlet'), ('Hamilton STARlet', 'Hamilton STARlet'), ('Seegene Nimbus', 'Seegene Nimbus'), ('CFX 96Dx', 'CFX 96Dx'), ('SeePrep32', 'SeePrep32'), ('Labelling & Packaging Instruction', 'Labelling & Packaging Instruction'), ('Seegene STARlet-VCMS', 'Seegene STARlet-VCMS'), ('Seegene STARlet-UV Light Kit', 'Seegene STARlet-UV Light Kit')], default='Seegene STARlet', max_length=100, verbose_name='장비이름'),
        ),
    ]
