# Generated by Django 4.0.3 on 2022-04-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instrument_SN', models.CharField(max_length=50)),
                ('Inspector', models.CharField(max_length=20, null=True)),
                ('Start_Date', models.DateField()),
                ('Completed_Date', models.DateField()),
                ('Status', models.CharField(max_length=20)),
                ('Revision', models.CharField(max_length=50, null=True)),
                ('SW_Version', models.CharField(max_length=50)),
                ('FV2_Version', models.CharField(max_length=50)),
                ('FW_PipetteCh', models.CharField(max_length=50)),
                ('FW_Xdrive', models.CharField(max_length=50)),
                ('FW_Master', models.CharField(max_length=50)),
                ('Computer_SN', models.CharField(max_length=50)),
            ],
        ),
    ]
