# Generated by Django 4.0.3 on 2022-06-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X6',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X7',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X8',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y6',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y7',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y8',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z6',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z7',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z8',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
