# Generated by Django 4.0.3 on 2022-07-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Acc_Damage',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Acc_Missing',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Back',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Binding',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Front',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Labels',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Left',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Packaging_Box',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Right',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Shock_Watch',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Top',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Transport_Jig',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Wooden_Pallet',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Barcode_Report',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_CoverSafety_Report',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Declaration',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Declaration_HHS',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_ElectricalSafety_Report',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Measurement_Protocol',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Position_Report',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Computer_SN',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='ElectricalTest_GroundResistance',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='ElectricalTest_HiPotential',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='ElectricalTest_PowerLED',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='ElectricalTest_PowerSWFunction',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='FV2_Version',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='FW_Master',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='FW_PipetteCh',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='FW_Xdrive',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Adjust',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Autoload',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_BarcodeCarrier',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_CalibrationTool',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Noise',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_SN1',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_SN2',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_SN3',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_SN4',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_SN5',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_SN6',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_SN7',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_SN8',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Inspector',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Name',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_Barcode',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_CoverSafety',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_HHS_RPM',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_HHS_SN',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_HHS_temperature',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_Loading_4mfxCarrier',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_Loading_TipCarrier',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_Loading_TubeCarrier',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_Loading_mtpCarrier',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy1000ul1',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy1000ul2',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy1000ul3',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy1000ul4',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy1000ul5',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy1000ul6',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy1000ul7',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy1000ul8',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy300ul1',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy300ul2',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy300ul3',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy300ul4',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy300ul5',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy300ul6',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy300ul7',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Accuracy300ul8',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision1000ul1',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision1000ul2',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision1000ul3',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision1000ul4',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision1000ul5',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision1000ul6',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision1000ul7',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision1000ul8',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision300ul1',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision300ul2',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision300ul3',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision300ul4',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision300ul5',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision300ul6',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision300ul7',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_VFV_Precision300ul8',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Perfomance_XYZpositioning',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Revision',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='SW_Version',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Status',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
