# Generated by Django 4.0.3 on 2022-04-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='Completed_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Computer_SN',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='FV2_Version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='FW_Master',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='FW_PipetteCh',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='FW_Xdrive',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='SW_Version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Start_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
