# Generated by Django 4.0.3 on 2022-06-07 04:10

import Inspectionapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instrumentapp', '0001_initial'),
        ('Inspectionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=30)),
                ('Subcategory', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='id',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Binding_Image',
            field=models.ImageField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Labels_Image',
            field=models.ImageField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Packaging_Box_Image',
            field=models.ImageField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Shock_Watch_Image',
            field=models.ImageField(blank=True, upload_to=Inspectionapp.models.Inspection.test_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Transport_Jig_Image',
            field=models.ImageField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Video',
            field=models.FileField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Wooden_Pallet_Image',
            field=models.ImageField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Barcode_Report_File',
            field=models.FileField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Attachment_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_CoverSafety_Report_File',
            field=models.FileField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Attachment_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Files',
            field=models.FileField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.test_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Position_Report_File',
            field=models.FileField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Attachment_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Instrument_SN',
            field=models.OneToOneField(db_column='Instrument_SN', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Inspection', serialize=False, to='Instrumentapp.instrument'),
        ),
    ]
