# Generated by Django 3.2.5 on 2022-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0002_auto_20220719_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Binding_Image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Labels_Image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Packaging_Box_Image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Shock_Watch_Image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Transport_Jig_Image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Video',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Wooden_Pallet_Image',
            field=models.TextField(blank=True),
        ),
    ]
