# Generated by Django 3.2.5 on 2022-07-19 11:24

import Inspectionapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0002_alter_inspection_appearance_acc_damage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Binding_Image',
            field=models.ImageField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Labels_Image',
            field=models.ImageField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Packaging_Box_Image',
            field=models.ImageField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Shock_Watch_Image',
            field=models.ImageField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.test_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Transport_Jig_Image',
            field=models.ImageField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Video',
            field=models.FileField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Wooden_Pallet_Image',
            field=models.ImageField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
    ]
