# Generated by Django 4.0.3 on 2022-04-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0002_alter_inspection_appearance_binding_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=30)),
                ('Subcategory', models.CharField(max_length=60)),
            ],
        ),
    ]
