# Generated by Django 4.0.3 on 2022-05-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0003_inspection_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='Attachment_STARLINE_Report',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
