# Generated by Django 3.2.5 on 2022-07-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0003_auto_20220719_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Barcode_Report',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_CoverSafety_Report',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Declaration',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Declaration_HHS',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_ElectricalSafety_Report',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Measurement_Protocol',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Position_Report',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
