# Generated by Django 4.0.3 on 2022-06-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0003_rename_completed_date_inspection_completedt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='Start_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
