# Generated by Django 4.0.3 on 2022-04-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0003_inspection_name_alter_inspection_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='Computer_SN',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='FV2_Version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='FW_Master',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='FW_PipetteCh',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='FW_Xdrive',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Inspector',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Revision',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='SW_Version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
