# Generated by Django 4.0.3 on 2022-05-16 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0004_inspection_attachment_starline_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='Attachment_STARLINE_Report',
        ),
    ]
