# Generated by Django 4.0.3 on 2022-06-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0004_alter_inspection_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
