# Generated by Django 4.0.3 on 2022-05-16 08:25

import Inspectionapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0005_remove_inspection_attachment_starline_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Binding_Image',
            field=models.ImageField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Labels_Image',
            field=models.ImageField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Packaging_Box_Image',
            field=models.ImageField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Shock_Watch_Image',
            field=models.ImageField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Transport_Jig_Image',
            field=models.ImageField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Video',
            field=models.FileField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Appearance_Wooden_Pallet_Image',
            field=models.ImageField(blank=True, upload_to=Inspectionapp.models.Inspection.Appearance_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Barcode_Report_File',
            field=models.FileField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Attachment_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_CoverSafety_Report_File',
            field=models.FileField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Attachment_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Files',
            field=models.FileField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Attachment_image_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='Attachment_Position_Report_File',
            field=models.FileField(blank=True, null=True, upload_to=Inspectionapp.models.Inspection.Attachment_image_path),
        ),
    ]
