# Generated by Django 4.0.3 on 2022-04-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0005_inspection_appearance_acc_damage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_X8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Y8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_PIP_Z8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_XArm_Diff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_XArm_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_XArm_right',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xdev1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xdev2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xdev3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xdev4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xdev5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xdev6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xdev7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xdev8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xtilt1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xtilt2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xtilt3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xtilt4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xtilt5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xtilt6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xtilt7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Xtilt8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Ytilt1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Ytilt2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Ytilt3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Ytilt4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Ytilt5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Ytilt6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Ytilt7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='HardWare_Ytilt8',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
