# Generated by Django 4.0.3 on 2022-04-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0006_alter_inspection_hardware_pip_x1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='HardWare_CalibrationTool',
        ),
    ]
