# Generated by Django 4.0.3 on 2022-06-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0006_rename_completedt_inspection_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='Completed_Date',
        ),
        migrations.AddField(
            model_name='inspection',
            name='CompleteDt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
