# Generated by Django 3.2.5 on 2022-07-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inspection_Path', models.FilePathField(allow_files=False, allow_folders=True, default='/home/windows/품질관리_장비inspection', verbose_name='수입검사 파일 위치')),
                ('Nonconformance_Path', models.FilePathField(allow_files=False, allow_folders=True, default='/home/windows/품질관리_장비inspection', verbose_name='부적합검사 파일 위치')),
            ],
        ),
    ]
