# Generated by Django 3.2.5 on 2022-07-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Inspection_Path',
            field=models.FilePathField(allow_files=False, allow_folders=True, default='/home/windows/품질관리_장비inspection', path='/home/windows/품질관리_장비inspection', verbose_name='수입검사 파일 위치'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='Nonconformance_Path',
            field=models.FilePathField(allow_files=False, allow_folders=True, default='/home/windows/품질관리_장비inspection', path='/home/windows/품질관리_장비inspection', verbose_name='부적합검사 파일 위치'),
        ),
    ]
