# Generated by Django 3.2.5 on 2022-07-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settingsapp', '0009_alter_settings_inspection_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='File_Upload',
            field=models.FileField(default='\\\\10.10.102.76\\추출장비다원화팀\\테스트', upload_to='\\\\10.10.102.76\\추출장비다원화팀\\테스트'),
        ),
    ]
