# Generated by Django 4.0.3 on 2022-07-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settingsapp', '0012_alter_settings_inspection_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='File_Upload',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Inspection_Path',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='Nonconformance_Path',
        ),
        migrations.AddField(
            model_name='settings',
            name='Path',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='수입검사 성적서 경로'),
        ),
        migrations.AddField(
            model_name='settings',
            name='Path_Describe',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='성적서경로 설명'),
        ),
    ]
