# Generated by Django 4.0.3 on 2022-07-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settingsapp', '0013_remove_settings_file_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='Type',
            field=models.CharField(choices=[('수입검사', '수입검사'), ('완제품검사', '완제품검사')], default=1, max_length=40, verbose_name='구분'),
            preserve_default=False,
        ),
    ]
