# Generated by Django 4.0.3 on 2022-07-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settingsapp', '0014_settings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Path',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='폴더경로'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='Path_Describe',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='설명'),
        ),
    ]
