# Generated by Django 4.0.3 on 2022-05-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('Managemant_Num', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('Instrument', models.CharField(max_length=60)),
                ('Tool_Machine', models.CharField(max_length=60)),
                ('State', models.CharField(max_length=60)),
                ('Type', models.CharField(max_length=60)),
            ],
        ),
    ]
