# Generated by Django 4.0.3 on 2022-07-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='ERP_Name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='ERP명칭'),
        ),
    ]
