# Generated by Django 4.0.3 on 2022-05-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='Calibration_Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Validation_Date',
            field=models.DateField(auto_now=True),
        ),
    ]
