# Generated by Django 4.0.3 on 2022-05-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0003_rename_managemant_num_calibration_managemantnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibration',
            old_name='Tool_Machine',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='ManagemantNum',
            new_name='Managemant_Num',
        ),
    ]
