# Generated by Django 4.0.3 on 2022-05-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0005_calibration_calibration_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='Cal_Location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='calibration',
            name='CalibrationCycle',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='calibration',
            name='ERP_Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='ERP_Nm',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='calibration',
            name='ERP_Num',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='calibration',
            name='ERP_Sticker',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Etc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Hide',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Main_Manager',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Manufacturer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Model_Serial',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Previous_Manage_Num',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Real_Calibration_Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Store_Location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Sub_Manager',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
