# Generated by Django 4.0.3 on 2022-05-18 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0007_rename_calibration_date_calibration_calibrationdt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibration',
            name='Etc',
        ),
        migrations.RemoveField(
            model_name='calibration',
            name='Hide',
        ),
        migrations.RemoveField(
            model_name='calibration',
            name='Previous_Manage_Num',
        ),
        migrations.RemoveField(
            model_name='calibration',
            name='Store_Location',
        ),
    ]
