# Generated by Django 4.0.3 on 2022-05-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0008_remove_calibration_etc_remove_calibration_hide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='Etc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Hide',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Previous_Manage_Num',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Store_Location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
