# Generated by Django 4.0.3 on 2022-07-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0009_calibration_etc_calibration_hide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibration',
            name='Hide',
        ),
        migrations.AddField(
            model_name='calibration',
            name='is_Hide',
            field=models.BooleanField(default=False, verbose_name='공개여부'),
        ),
    ]
