# Generated by Django 4.0.3 on 2022-07-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0010_remove_calibration_hide_calibration_is_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='is_Hide',
            field=models.BooleanField(default=True, verbose_name='공개여부'),
        ),
    ]
