# Generated by Django 4.0.3 on 2022-07-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0011_alter_calibration_is_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='CalibrationDt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='ValidationDt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
