# Generated by Django 4.0.3 on 2022-07-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0012_alter_calibration_calibrationdt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='CalibrationDt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='ValidationDt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
