# Generated by Django 4.0.3 on 2022-07-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0013_alter_calibration_calibrationdt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Managemant_Num',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
