# Generated by Django 4.0.3 on 2022-07-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0014_calibration_id_alter_calibration_managemant_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='Cal_Location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='CalibrationCycle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Description',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='ERP_Date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='ERP_Nm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='ERP_Num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='ERP_Sticker',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Etc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Main_Manager',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Manufacturer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Model_Serial',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Previous_Manage_Num',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='State',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Store_Location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Sub_Manager',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Type',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='is_Hide',
            field=models.BooleanField(default=True, null=True, verbose_name='공개여부'),
        ),
    ]
