# Generated by Django 4.0.3 on 2022-07-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0015_alter_calibration_cal_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='Cal_Location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='교정처'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='CalibrationCycle',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='교정주기'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='CalibrationDt',
            field=models.DateField(blank=True, null=True, verbose_name='교정일자'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Calibration_Serial',
            field=models.CharField(blank=True, max_length=60, verbose_name='시리얼번호'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Description',
            field=models.CharField(max_length=60, null=True, verbose_name='설비 및 계측기'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='ERP_Date',
            field=models.DateField(auto_now=True, null=True, verbose_name='ERP 취득일자'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='ERP_Nm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ERP명칭'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='ERP_Num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ERP 번호'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='ERP_Sticker',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ERP 라벨부착여부'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Etc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Instrument',
            field=models.CharField(max_length=60, verbose_name='장비명'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Main_Manager',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='관리책임자(정)'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Managemant_Num',
            field=models.CharField(max_length=30, unique=True, verbose_name='관리번호'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Manufacturer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='제조자'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Model_Serial',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='모델번호'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Previous_Manage_Num',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='구 관리번호'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Real_Calibration_Date',
            field=models.DateField(auto_now=True, verbose_name='실제유효기간'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='State',
            field=models.CharField(max_length=60, null=True, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Store_Location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='보관위치'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Sub_Manager',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='관리책임자(부)'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Type',
            field=models.CharField(max_length=60, null=True, verbose_name='교정유형'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='ValidationDt',
            field=models.DateField(blank=True, null=True, verbose_name='유효기간'),
        ),
    ]
