# Generated by Django 4.0.3 on 2022-07-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0016_alter_calibration_cal_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='Price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='구매가격'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='ERP_Num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ERP등록번호'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Instrument',
            field=models.CharField(max_length=60, verbose_name='대상'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Real_Calibration_Date',
            field=models.DateField(auto_now=True, verbose_name='실제교정일자'),
        ),
    ]
