# Generated by Django 4.0.3 on 2022-07-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0018_remove_calibration_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='State',
            field=models.CharField(choices=[('가능', '가능'), ('교정예정', '교정예정'), ('교정중', '교정중'), ('불가(고장)', '불가(고장)'), ('불가(기타)', '불가(기타)'), ('불가', '미등록'), ('불가', '(미입고)')], default='가능', max_length=32, verbose_name='상태'),
        ),
    ]
