# Generated by Django 4.0.3 on 2022-07-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0019_alter_calibration_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='State',
            field=models.CharField(choices=[('가능', '가능'), ('교정예정', '교정예정'), ('교정중', '교정중'), ('불가(고장)', '불가(고장)'), ('불가(기타)', '불가(기타)'), ('불가(미등록)', '불가(미등록)'), ('불가(미입고)', '불가(미입고)')], default='가능', max_length=32, verbose_name='상태'),
        ),
    ]
