# Generated by Django 4.0.3 on 2022-07-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0022_alter_calibration_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='Price',
            field=models.IntegerField(default=1, verbose_name='가격'),
            preserve_default=False,
        ),
    ]
