# Generated by Django 4.0.3 on 2022-07-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0024_alter_calibration_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibration',
            options={'verbose_name': '교정Tool 데이터', 'verbose_name_plural': '교정Tool 데이터'},
        ),
        migrations.AlterModelTable(
            name='calibration',
            table='Hardwareapp_calibration',
        ),
    ]
