# Generated by Django 4.0.3 on 2022-07-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardwareapp', '0025_alter_calibration_options_alter_calibration_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibration',
            old_name='Cal_Location',
            new_name='CAL_Company',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='CalibrationCycle',
            new_name='CAL_Cycle',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='CalibrationDt',
            new_name='CAL_Date',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='Type',
            new_name='CAL_Type',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='Sub_Manager',
            new_name='Deputy_Head',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='ERP_Sticker',
            new_name='ERP_Label_State',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='ERP_Nm',
            new_name='ERP_Name',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='Description',
            new_name='Equipment_Name',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='ValidationDt',
            new_name='Expiration_Date',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='Main_Manager',
            new_name='Head',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='Managemant_Num',
            new_name='Mgt_Num',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='Model_Serial',
            new_name='Model_Num',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='Previous_Manage_Num',
            new_name='Prev_Mgt_Num',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='Etc',
            new_name='Ramarks',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='Calibration_Serial',
            new_name='Serial_Num',
        ),
        migrations.RenameField(
            model_name='calibration',
            old_name='State',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='calibration',
            name='Manufacturer',
        ),
        migrations.RemoveField(
            model_name='calibration',
            name='Real_Calibration_Date',
        ),
        migrations.AddField(
            model_name='calibration',
            name='CAL_Plan_Check',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='교정계획확인'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='CAL_Plan_Company',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='교정예정처'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='CAL_Plan_Date',
            field=models.DateField(auto_now=True, verbose_name='교정계획일자'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='CAL_Plan_Price',
            field=models.IntegerField(blank=True, null=True, verbose_name='교정 예정금액'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='Expiration_YYMM',
            field=models.DateField(auto_now=True, verbose_name='유효년월'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='MFG_Company',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Instrument',
            field=models.CharField(choices=[('공용', '공용'), ('Seegene STARlet', 'Seegene STARlet'), ('Hamilton STARlet', 'Hamilton STARlet'), ('Seegene Nimbus', 'Seegene Nimbus'), ('CFX 96Dx', 'CFX 96Dx'), ('Seeprep32', 'Seeprep32'), ('SGRT', 'SGRT'), ('AIOS', 'AIOS'), ('VCMS', 'VCMS'), ('모바일스테이션', '모바일스테이션'), ('기타', '기타')], default='Seegene STARlet', max_length=32, verbose_name='장비'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='Price',
            field=models.IntegerField(blank=True, null=True, verbose_name='구매가격'),
        ),
    ]
