# Generated by Django 4.0.3 on 2022-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instrument_SN', models.CharField(max_length=50)),
                ('Shock_Watch', models.CharField(max_length=20, null=True)),
                ('Binding', models.CharField(max_length=20, null=True)),
                ('Labels', models.CharField(max_length=20, null=True)),
                ('Packaging_Box', models.CharField(max_length=20, null=True)),
                ('Wooden_Pallet', models.CharField(max_length=20, null=True)),
                ('Transport_Jig', models.CharField(max_length=20, null=True)),
                ('Shock_Watch_Image', models.ImageField(null=True, upload_to='Appearance/')),
                ('Binding_Image', models.ImageField(null=True, upload_to='Appearance/')),
                ('Labels_Image', models.ImageField(null=True, upload_to='Appearance/')),
                ('Packaging_Box_Image', models.ImageField(null=True, upload_to='Appearance/')),
                ('Wooden_Pallet_Image', models.ImageField(null=True, upload_to='Appearance/')),
                ('Transport_Jig_Image', models.ImageField(null=True, upload_to='Appearance/')),
                ('Video', models.FileField(null=True, upload_to='video/')),
            ],
        ),
    ]
