# Generated by Django 4.0.3 on 2022-04-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appearanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='Image',
            field=models.ImageField(null=True, upload_to='Appearance/'),
        ),
    ]
