# Generated by Django 4.0.3 on 2022-04-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appearanceapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appearance',
        ),
    ]
