# Generated by Django 4.0.3 on 2022-04-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appearanceapp', '0002_appearance_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='Image',
            new_name='Binding_Image',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='Acc_Damage',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='Acc_Missing',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='Back',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='Front',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='Left',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='Right',
        ),
        migrations.AddField(
            model_name='appearance',
            name='Labels_Image',
            field=models.ImageField(null=True, upload_to='Appearance/'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='Packaging_Box_Image',
            field=models.ImageField(null=True, upload_to='Appearance/'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='Shock_Watch_Image',
            field=models.ImageField(null=True, upload_to='Appearance/'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='Transport_Jig_Image',
            field=models.ImageField(null=True, upload_to='Appearance/'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='Wooden_Pallet_Image',
            field=models.ImageField(null=True, upload_to='Appearance/'),
        ),
    ]
