# Generated by Django 4.0.3 on 2022-04-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appearanceapp', '0004_appearance_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appearance',
        ),
    ]
